package com.termux.app.fragments.settings;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.preference.PreferenceFragmentCompat;
import androidx.preference.PreferenceManager;

import com.termux.R;
import com.termux.shared.termux.TermuxConstants;
import com.termux.shared.logger.Logger;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Set;

public class NewTermuxPreferencesFragment extends PreferenceFragmentCompat implements SharedPreferences.OnSharedPreferenceChangeListener {

    private static final String LOG_TAG = "NewTermuxPreferencesFragment";

    @Override
    public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
        setPreferencesFromResource(R.xml.newtermux_preferences, rootKey);
    }

    @Override
    public void onResume() {
        super.onResume();
        getPreferenceScreen().getSharedPreferences().registerOnSharedPreferenceChangeListener(this);
    }

    @Override
    public void onPause() {
        super.onPause();
        getPreferenceScreen().getSharedPreferences().unregisterOnSharedPreferenceChangeListener(this);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) {
        if ("default_shell".equals(key) || "omz_theme".equals(key) || "omz_plugins".equals(key) || "enable_oh_my_zsh".equals(key)) {
            updateZshConfiguration(sharedPreferences);
        }
    }

    private void updateZshConfiguration(SharedPreferences prefs) {
        String shell = prefs.getString("default_shell", "bash");
        boolean enableOMZ = prefs.getBoolean("enable_oh_my_zsh", true);
        String theme = prefs.getString("omz_theme", "robbyrussell");
        Set<String> plugins = prefs.getStringSet("omz_plugins", null);

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by NewTermux Settings
");
        
        if (enableOMZ) {
            sb.append("export ZSH="$HOME/.oh-my-zsh"
");
            sb.append("ZSH_THEME="").append(theme).append(""
");
            
            sb.append("plugins=(");
            if (plugins != null) {
                for (String p : plugins) {
                    sb.append(p).append(" ");
                }
            }
            sb.append(")
");
            
            sb.append("source $ZSH/oh-my-zsh.sh
");
        }

        sb.append("
# Custom aliases and exports
");
        sb.append("alias ls='ls --color=auto'
");
        
        // Write to .zshrc
        try {
            File zshrc = new File(TermuxConstants.TERMUX_HOME_DIR_PATH, ".zshrc");
            try (FileOutputStream fos = new FileOutputStream(zshrc)) {
                fos.write(sb.toString().getBytes(StandardCharsets.UTF_8));
            }
            Logger.logInfo(LOG_TAG, "Updated .zshrc based on settings");
        } catch (Exception e) {
            Logger.logError(LOG_TAG, "Failed to update .zshrc: " + e.getMessage());
        }
    }
}
